### ISSUE TITLE
Allow use of ConEmu

### ISSUE THREAD

**Issue by ThomIves** [ranjandatta/brackets-open-in-linux-terminal#4]
Great plugin! Thanks! Can you add support for ConEmu (x64), such as "C:\Program Files\ConEmu\ConEmu64.exe"? Or maybe even the ability to enter in a different one all together by just specifying where to launch it from? And, if not too much trouble, a way to pass in intial command line arguments when it's started. 

Example of Sublime technique:
```
{
  // Replace with your own path to cmder.exe
  "terminal": "C:\\Program Files\\cmder_mini\\cmder.exe",
  "parameters": ["/START", "%CWD%"]
}
```

**Comment by ranjandatta** [comment]
Unfortunately I do not use windows and have no way of testing the code. So I would request @anandnarla to contribute the code

**Comment by anandnarla** [comment]
I'd love to do that. I'll start working on it and let you people know once I am done.

**Comment by ThomIves** [comment]
Awesome Anand. Thanks

**Comment by anandnarla** [comment]
@ThomIves, I have added the support for ConEmu for both x64 and x86 versions. I have tried to work on the suggestion that you mentioned about adding support for user to specify the location of the console's exe also, but it is taking some time. in the mean time you can use this version which has hard coded support for ConEmu. I'll update you once i am done with that thing as well.

@ranjandatta, can you please check and accept the pull request #5

**Comment by ranjandatta** [comment]
Merged and published, Closing this issue
